name: hpcmlx
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel
  - pip:
    - Django>=4.2,<4.3
    - djangorestframework>=3.14.0
    - psycopg2-binary>=2.9.0
